ft_demo:
  timeout: 10
  scheme: http
  host: 192.168.4.165:8443
  headers:
    Content-Type: application/json
    # 注入jwt认证信息，case可直接引入复用，前提是login/auth接口响应的字段保持一致
    Authorization: "${token_type} ${access_token}"
